In [129]:
from itertools import combinations
import numpy as np
from scipy.stats import rankdata, kendalltau

In [2]:
class graph:
    def __init__(self, value):
        self.y = value

In [8]:
def sample_preference_pairs(graphs):
    c = [(a, b, check_util(graphs, a,b)) for a, b in combinations(range(len(graphs)), 2)]
    return np.array(c)

def check_util(data, index_a, index_b):
    a = data[index_a]
    b = data[index_b]
    util_a = a.y
    util_b = b.y
    if util_a >= util_b:
        return 1
    else:
        return 0

In [7]:
g1 = graph(2.7)
g2 = graph(3.1)
g3 = graph(2.6)
g4 = graph(5.4)
g5 = graph(-1.3)
graphs = [g1,g2,g3,g4,g5]

In [25]:
prefs = sample_preference_pairs(graphs)

In [180]:
prefs

array([[0, 1, 0],
       [0, 2, 1],
       [0, 3, 0],
       [0, 4, 1],
       [1, 2, 1],
       [1, 3, 0],
       [1, 4, 1],
       [2, 3, 0],
       [2, 4, 1],
       [3, 4, 1]])

In [16]:
pre_ranking = rankdata([g.y for g in graphs])
pre_ranking

array([3., 4., 2., 5., 1.])

In [151]:
import numpy as np

# Define the array
arr = np.array([
    [0, 1, 0],
    [0, 2, 1],
    [0, 3, 0],
    [0, 4, 1],
    [1, 2, 1],
    [1, 3, 0],
    [1, 4, 1],
    [2, 3, 0],
    [2, 4, 1],
    [3, 4, 1]
])

# Create a mask for rows where the last element is 0
mask = arr[:, 2] == 0

# Switch the first and second indices for rows where the mask is True
arr[mask] = arr[mask][:, [1, 0, 2]]

# Remove the last index
arr = arr[:, :2]

print(arr)

[[1 0]
 [0 2]
 [3 0]
 [0 4]
 [1 2]
 [3 1]
 [1 4]
 [3 2]
 [2 4]
 [3 4]]


In [178]:
prefs

array([[0, 1, 0],
       [0, 2, 1],
       [0, 3, 0],
       [0, 4, 1],
       [1, 2, 1],
       [1, 3, 0],
       [1, 4, 1],
       [2, 3, 0],
       [2, 4, 1],
       [3, 4, 1]])

In [181]:
def preprocess_predictions(arr):
    # Create a mask for rows where the last element is 0
    mask = arr[:, 2] == 0
    # Switch the first and second indices for rows where the mask is True
    arr[mask] = arr[mask][:, [1, 0, 2]]
    # Remove the last index
    arr = arr[:, :2]
    return arr

# Example usage
arr = np.array([
    [0, 1, 0],
    [0, 2, 1],
    [0, 3, 0],
    [0, 4, 1],
    [1, 2, 1],
    [1, 3, 0],
    [1, 4, 1],
    [2, 3, 0],
    [2, 4, 1],
    [3, 4, 1]
])

# Call the function to ensure the array is reset each time
result = preprocess_predictions(arr.copy())
print(result)

[[1 0]
 [0 2]
 [3 0]
 [0 4]
 [1 2]
 [3 1]
 [1 4]
 [3 2]
 [2 4]
 [3 4]]


In [199]:
def retrieve_preference_counts_from_predictions(arr, max_range):
    first_index_elements = arr[:, 0]

    # Extract the first column
    first_index_elements = arr[:, 0]
    
    # Define the range of possible numbers (assuming 0 to 3 for this example)
    possible_numbers = range(max_range)
    
    # Initialize the dictionary with all possible numbers
    element_counts = {num: 0 for num in possible_numbers}
    print(element_counts)
    
    # Count the occurrences of each element in the first index
    unique_elements, counts = np.unique(first_index_elements, return_counts=True)
    
    # Update the dictionary with the actual counts
    element_counts.update(dict(zip(unique_elements, counts)))
    
    return element_counts

In [216]:
res = retrieve_preference_counts_from_predictions(result, 5)

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0}


In [217]:
res

{0: 2, 1: 3, 2: 1, 3: 4, 4: 0}

In [225]:
post_ranking = rankdata(list(res.values()))

In [226]:
post_ranking

array([3., 4., 2., 5., 1.])

In [224]:
pre_ranking

array([3., 4., 2., 5., 1.])

In [227]:
kendalltau(pre_ranking, post_ranking)

SignificanceResult(statistic=0.9999999999999999, pvalue=0.016666666666666666)